In [ ]:
import torch
import torch.nn as nn
!pip install torchinfo
from torchinfo import summary

**1. Simple Neural Network (y_pred = sigmoid(w.x + b))**

In [ ]:
class SimpleNN(nn.Module):
    def __init__(self,features):
        super().__init__()
        self.linear = nn.Linear(features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,x):
        out = self.linear(x)
        out = self.sigmoid(out)
        return out

In [50]:
input_ = torch.rand(10,5,dtype=torch.float32)
y = torch.randint(0,2,(input_.shape[0],),dtype=torch.float32)
input_, y

(tensor([[0.4707, 0.4460, 0.3486, 0.4919, 0.1908],
         [0.4069, 0.6509, 0.9890, 0.7088, 0.8466],
         [0.1705, 0.3100, 0.5128, 0.5636, 0.5657],
         [0.0325, 0.3805, 0.9079, 0.1862, 0.6594],
         [0.5207, 0.9798, 0.4449, 0.8178, 0.8207],
         [0.8311, 0.4330, 0.0568, 0.2968, 0.7086],
         [0.1490, 0.5285, 0.2788, 0.2859, 0.3578],
         [0.7069, 0.7162, 0.7237, 0.2875, 0.9428],
         [0.1256, 0.3515, 0.9354, 0.8724, 0.2581],
         [0.2340, 0.5246, 0.6592, 0.3458, 0.1944]]),
 tensor([1., 1., 0., 1., 0., 0., 1., 0., 0., 1.]))

In [56]:
learning_rate = 0.2
epochs = 10
loss_function = nn.BCELoss()

In [57]:
model = SimpleNN(input_.shape[1])
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)
for i in range(epochs):
    y_pred = model(input_)
    loss = loss_function(y_pred,y.view(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f"Epoch {i+1} - Loss: {loss}")

Epoch 1 - Loss: 0.6418163776397705
Epoch 2 - Loss: 0.6393764615058899
Epoch 3 - Loss: 0.6373001933097839
Epoch 4 - Loss: 0.6355092525482178
Epoch 5 - Loss: 0.6339421272277832
Epoch 6 - Loss: 0.6325508952140808
Epoch 7 - Loss: 0.6312979459762573
Epoch 8 - Loss: 0.6301542520523071
Epoch 9 - Loss: 0.6290966272354126
Epoch 10 - Loss: 0.6281075477600098


In [58]:
print(f"Weight-gradient: {model.linear.weight}")
print(f"Bias-gradient: {model.linear.bias}")
summary(model)

Weight-gradient: Parameter containing:
tensor([[-0.4122, -0.1524,  0.4384, -0.3751, -0.4748]], requires_grad=True)
Bias-gradient: Parameter containing:
tensor([0.4049], requires_grad=True)


Layer (type:depth-idx)                   Param #
SimpleNN                                 --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

**2. Deep Neural Network (y_pred = sigmoid(w.x + b))**

In [ ]:
class DeepNN(nn.Module):
    def __init__(self,features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(features,5),
            nn.ReLU(),
            nn.Linear(5,1),
            nn.Sigmoid()
        )

    def forward(self,x):
        out = self.network(x)
        return out

In [ ]:
deep_model = DeepNN(input_.shape[1])
out_ = deep_model(input_)
print("Output of NN: ",output_)

Output of NN:  tensor([[0.6732],
        [0.6889],
        [0.6687],
        [0.6618],
        [0.6204],
        [0.5884],
        [0.6445],
        [0.6791],
        [0.6000],
        [0.6492]], grad_fn=<SigmoidBackward0>)


In [ ]:
summary(deep_model)

Layer (type:depth-idx)                   Param #
DeepNN                                   --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       30
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       6
│    └─Sigmoid: 2-4                      --
Total params: 36
Trainable params: 36
Non-trainable params: 0